### ISSUE TITLE
import douyin报错

### ISSUE THREAD

**Issue by carter115** [Python3WebSpider/DouYin#1]
import douyin
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-2f90f35ac933>", line 1, in <module>
    import douyin
  File "C:\Program Files\JetBrains\PyCharm Community Edition 181.3986.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\douyin\__init__.py", line 2, in <module>
    import douyin.handlers
  File "C:\Program Files\JetBrains\PyCharm Community Edition 181.3986.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\douyin\handlers\__init__.py", line 2, in <module>
    from douyin.handlers.file import FileHandler
  File "C:\Program Files\JetBrains\PyCharm Community Edition 181.3986.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\douyin\handlers\file.py", line 5, in <module>
    import aiohttp
  File "C:\Program Files\JetBrains\PyCharm Community Edition 181.3986.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "C:\Program Files\JetBrains\PyCharm Community Edition 181.3986.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\client.py", line 18, in <module>
    from . import client_exceptions, client_reqrep
  File "C:\Program Files\JetBrains\PyCharm Community Edition 181.3986.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 17, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "C:\Program Files\JetBrains\PyCharm Community Edition 181.3986.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\helpers.py", line 166, in <module>
    @attr.s(frozen=True, slots=True)
TypeError: attributes() got an unexpected keyword argument 'frozen'

**Comment by carter115** [comment]
python 3.6.6 + aiohttp 3.4 会出现这个报错。换回来python 3.5 就可以了。
